# Generated by Django 4.0.3 on 2024-09-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmsApp', '0002_post_date_created_post_date_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
